### ISSUE TITLE
Failed to load libseekcamera.so from default system paths

### ISSUE THREAD

**Issue by ranjitkathiriya** [seekthermal/seekcamera-python#14]
Hello there,

I am getting below error, I am using seek thermal camera Monosic core. 

Traceback (most recent call last):
  File "/home/kuka-ai/Desktop/Ranjit/seekcamera-python/seekcamera/_clib.py", line 107, in configure_dll
    _cdll = ctypes.CDLL(lib)
  File "/home/kuka-ai/anaconda3/envs/cowhealth/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libseekcamera.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/seekcamera-opencv.py", line 166, in <module>
    main()
  File "examples/seekcamera-opencv.py", line 131, in main
    with SeekCameraManager(SeekCameraIOType.USB) as manager:
  File "/home/kuka-ai/Desktop/Ranjit/seekcamera-python/seekcamera/camera.py", line 543, in __init__
    _clib.configure_dll()
  File "/home/kuka-ai/Desktop/Ranjit/seekcamera-python/seekcamera/_clib.py", line 109, in configure_dll
    raise RuntimeError("Failed to load %s from default system paths" % lib)
RuntimeError: Failed to load libseekcamera.so from default system paths

**Comment by emartin-216** [comment]
Hello,

Do you remember how you solved this issue?

**Comment by ranjitkathiriya** [comment]
> libseekcamera.so

https://developer.thermal.com/
You have to install the latest SDK which is SEEK THERMAL SDK - v4.1, 

The Python interface sits on top of the Seek Thermal SDK v4.x.
