### ISSUE TITLE
Failed to load libseekcamera.so from default system paths

### ISSUE THREAD

**Issue by emartin-216** [seekthermal/seekcamera-python#18]
Hi,

I have struggled to run this code, and I believe I'm missing something from the installation instructions that is causing this but I am not sure what. When I try to run **pip install -e .**, I get permission errors. Could this be causing the code to not work?

Below is the following error message:

Traceback (most recent call last):
  File "/home/pi/Documents/libseek-thermal-master/examples/seekcamera-python/seekcamera/_clib.py", line 107, in configure_dll
    _cdll = ctypes.CDLL(lib)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libseekcamera.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "seekcamera-opencv.py", line 166, in <module>
    main()
  File "seekcamera-opencv.py", line 131, in main
    with SeekCameraManager(SeekCameraIOType.USB) as manager:
  File "/home/pi/Documents/libseek-thermal-master/examples/seekcamera-python/seekcamera/camera.py", line 543, in __init__
    _clib.configure_dll()
  File "/home/pi/Documents/libseek-thermal-master/examples/seekcamera-python/seekcamera/_clib.py", line 109, in configure_dll
    raise RuntimeError("Failed to load %s from default system paths" % lib)
RuntimeError: Failed to load libseekcamera.so from default system paths

**Comment by mq-mattiasjuhl** [comment]
It can't find libseekcamer.so

A quick and hacky way to get around this is setting the correct path in  _clib.py.

If using the manual install it should be at the path
        /usr/local/lib/libseekcamera.so
otherwise try:
        whereis libseekcamera.so

Changing the lib variable in (line 97.) _clib.py (your location is  "/home/pi/Documents/libseek-thermal-master/examples/seekcamera-python/seekcamera/_clib.py")
from:
     lib = "libseekcamera.so" 
to (or what ever path it is in):
     lib = "/usr/local/lib/libseekcamera.so"

**Comment by blackadj** [comment]
Hi,

When i replace libseekcamera.so by /usr/local/lib/libseekcamera.so, i have the same error.
How i can solve this issue ?

**Comment by Alaa-osamaelsaid** [comment]
I have the same error as well what to do
